### ISSUE TITLE
Not working since 1.2.3 or so

### ISSUE THREAD

**Issue by MrJDerio** [dvmiyo/pguifinal#2]
Since the debug mode is available the enable button is not further working. It does not recognize the client and then is not working.

**Comment by dvmiyo** [comment]
It should be fixed now, please update the client

**Comment by MrJDerio** [comment]
Checked the update, just updates to 1.2.4 which still does not detect the client and does not enable the "Enable"button. Are you referring to another version?

**Comment by dvmiyo** [comment]
Hi, what operating system are you using and what client are you trying to
use it with, ex na, tw, japan/korea?

**Comment by MrJDerio** [comment]
I am using W10 and Eu client. Previous versions were working nice so when
is active the monitor seems like it can detect it. But since new versions
must detect the client before you can put it working, it does not work. If
you need something more just tell me.

**Comment by dvmiyo** [comment]
Are you sure you are pressing Enable after you have logged into your
character? I will try to make it a better process.

**Comment by MrJDerio** [comment]
There is no way to press enable on 1.2.3 and 1.2.4. There is just enable
log to press. Enable and disable seems not available to press.

**Comment by dvmiyo** [comment]
Hi, that's becuase once you press Enable log it will check if there already is a log.ini created, if not it creates one and enables the other button, and if it finds that there is it will still enable the button so the order to make it work is like this.
1. Press > Enable Log
2. Login to your character, tab to the launcher and press Enable

Now just switch back to your game and it should pop up after a few seconds, it may take a little while if it's the first time to log because it hasn't started to populate the log with info yet.

In 1.2.5 I make this process much easier, thanks for your patience!

**Comment by MrJDerio** [comment]
I've been trying it. I have fixed a problem it had when clicking Enable Log
that trowed a error message when the program was not on admin mode by
putting it in admin right mode. Seems like is working better now. It would
be nice to add a way to change the refresh frequency of the text, By the
way, problem fixed. Thanks for all your work, I do appreciate a lot your
work.

2016-03-29 15:42 GMT+02:00 Miyoko Hayakawa notifications@github.com:
